server.port=${SERVER_PORT}

spring.application.name=auth-service
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# Keycloak Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_SERVER_URL}/realms/${KEYCLOAK_REALM}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_SERVER_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

# Keycloak Admin Client Configuration
keycloak.server-url=${KEYCLOAK_SERVER_URL}
keycloak.realm=${KEYCLOAK_REALM}
keycloak.admin-username=${KEYCLOAK_ADMIN_USERNAME}
keycloak.admin-password=${KEYCLOAK_ADMIN_PASSWORD}
keycloak.client-id=${KEYCLOAK_CLIENT_ID}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}

# Application specific configuration
app.keycloak.realm=${KEYCLOAK_REALM}
app.keycloak.client-id=${KEYCLOAK_CLIENT_ID}
app.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}
app.keycloak.server-url=${KEYCLOAK_SERVER_URL}
app.keycloak.password-reset-redirect-uri=${PASSWORD_RESET_REDIRECT_URI}
app.keycloak.login-url=${KEYCLOAK_SERVER_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth?client_id=${KEYCLOAK_CLIENT_ID}&response_type=code&scope=openid&redirect_uri=${KEYCLOAK_REDIRECT_URI}
app.keycloak.google-login-url=${KEYCLOAK_SERVER_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth?client_id=${KEYCLOAK_CLIENT_ID}&response_type=code&scope=openid&kc_idp_hint=google&redirect_uri=${KEYCLOAK_REDIRECT_URI}

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true

logging.level.org.springframework.security=${LOG_LEVEL_SECURITY}
logging.level.org.keycloak=${LOG_LEVEL_KEYCLOAK}
logging.level.org.springframework=${LOG_LEVEL_SPRING}
