apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: keycloak
type: Opaque
data:
  # Values are base64 encoded
  # postgres-user: a2V5Y2xvYWs= (keycloak)
  # postgres-password: a2V5Y2xvYWs= (keycloak)
  # postgres-db: a2V5Y2xvYWs= (keycloak)
  postgres-user: a2V5Y2xvYWs=
  postgres-password: a2V5Y2xvYWs=
  postgres-db: a2V5Y2xvYWs=
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: keycloak
type: Opaque
data:
  # admin-user: YWRtaW4= (admin)
  # admin-password: YWRtaW4= (admin)
  admin-user: YWRtaW4=
  admin-password: YWRtaW4=

